### ISSUE TITLE
Exchange Scenarios (cross tokens) 用例坏掉了

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/ocap-playground#168] opened 2022-05-16 05:54 UTC
## Describe the bug
在 https://playground.staging.arcblock.io/full 中点击 “Exchange Scenarios (cross tokens)” 的两个 case 会报错

## Screenshots

<img width="731" alt="image" src="https://user-images.githubusercontent.com/8749615/168527809-2cc2ceff-63f9-49bf-bbba-9c84b0ed3b7b.png">
<img width="720" alt="image" src="https://user-images.githubusercontent.com/8749615/168528201-43bb9e50-5179-4cbd-8478-4ac465c52c11.png">

**Comment by donotlb** [comment] 2022-06-02 09:55
Duplicate of #170

**Closed by donotlb** 2022-06-02 09:55 UTC
